apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-eval-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-eval-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark-eval-sa
    namespace: default
---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-pi-eval
spec:
  sparkImage:
    productVersion: 3.5.5
  mode: cluster
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///stackable/spark/examples/jars/spark-examples_2.12-3.5.5.jar
  driver:
    config: {}
  executor:
    replicas: 1
    config: {}
